### ISSUE TITLE
investigate whether we can cache docker compose volumes

### ISSUE THREAD

**Issue by aelkiss** [hathitrust/github_actions#11]
When we run the tests, we do a `bundle install`, which can take a while. When running with docker compose, this uses something like:

```yaml
services:

  web:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    ...

volumes:
  gem_cache:
```

The question is if it's possible in github actions to cache the gem_cache volume to be re-used in future runs of the tests, similar to the `bundler-cache: true` option for https://github.com/ruby/setup-ruby. That would let us have our cake & eat it too in terms of using docker compose for the tests but also caching gems.
